# Generated by Django 3.1.13 on 2021-09-25 05:36

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import one_day_backend.accomo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=one_day_backend.accomo.models.get_file_path, verbose_name='게시글의 이미지')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
