# Generated by Django 3.1.13 on 2021-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210925_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='닉네임'),
        ),
    ]
