# Generated by Django 3.1.13 on 2021-09-24 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import one_day_backend.community.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_comments', to='community.postcomment'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=one_day_backend.community.models.get_file_path, verbose_name='게시글의 이미지'),
        ),
    ]
