# Generated by Django 3.1.13 on 2021-09-24 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210925_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='community.post'),
        ),
    ]
