# Generated by Django 3.1.13 on 2021-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210925_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.SmallIntegerField(default=0),
        ),
    ]
